#include "UltraSonic.h"
#include "gpio.h"
#include <avr/io.h>
#include <util/delay.h>
#include "icu.h"



uint8 g_edgeCount = 0;
uint16 g_timeHigh = 0;


/*
 *
 *  Initialize the ICU driver as required.
 *  Setup the ICU call back function.
 *  Setup the direction for the trigger pin as output pin through the GPIO driver.
 */

void Ultrasonic_init(void)
{

	/* Create configuration structure for ICU driver */
	Icu_ConfigType Icu_Config = {F_CPU_8,RISING};

	/*
	 * initialization ICU driver
	 */
	Icu_init(&Icu_Config);

	/* Enable Global Interrupt I-Bit */
	SREG |= (1<<7);

	/* Set the Call back function pointer in the ICU driver */
	Icu_setCallBack(Ultrasonic_edgeProcessing);



	/* Setup the direction for the trigger pin as output pin through the GPIO driver*/

	GPIO_setupPinDirection(PORTB_ID, PIN5_ID, PIN_OUTPUT);
}


/*
 * Send the Trigger pulse to the ultrasonic.
 */
void Ultrasonic_Trigger(void)
{
	/* Give 10us trigger pulse on trig. pin to HC-SR04 */

	g_timeHigh = 0;

	GPIO_writePin(PORTB_ID,PIN5_ID, 1);
	_delay_us(10);
	GPIO_writePin(PORTB_ID,PIN5_ID, 0);

}


/*
 * Send the trigger pulse by using Ultrasonic_Trigger function
 * Start the measurements by the ICU from this moment.
 */
uint16 Ultrasonic_readDistance(void)
{

	uint16 distance =0;

	Ultrasonic_Trigger(); // start the ultrasonic
	while(!(g_timeHigh));
	distance = 1 + (uint16)g_timeHigh/58;

	return distance;
}


/*
 * This is the call back function called by the ICU driver
 * This is used to calculate the high time (pulse time) generated by the ultrasonic sensor
 */
void Ultrasonic_edgeProcessing(void)
{
	g_edgeCount++;
		if(g_edgeCount == 1)
		{
			/*
			 * Clear the timer counter register to start measurements from the
			 * first detected rising edge
			 */
			Icu_clearTimerValue();
			/* Detect falling edge */
			Icu_setEdgeDetectionType(FALLING);
		}
		else if(g_edgeCount == 2)
		{
			/* Store the High time value */
			g_timeHigh = Icu_getInputCaptureValue();

		}
}
